USE REPORTERIA_GENERAL_CD03_GENERAL
CREATE TABLE DATAHU
( 
    CENTRO_ORIGEN varchar(50) NOT NULL 
    ,HU varchar(130) NOT NULL 
    ,ENTREGAS varchar(128) NOT NULL 
    ,UBICACION varchar(20)
    ,DESTINO varchar(29) NOT NULL
    ,FECHA_RECEPCION datetime  
);
SELECT * FROM DATAHU